deployment:
  tasks:
    - /bin/echo "Setting deployment path"
    - export DEPLOYPATH=/home/tuzgcpym/public_html/

    - /bin/echo "Installing dependencies"
    - /opt/cpanel/ea-nodejs20/bin/npm install

    - /bin/echo "Building project"
    - /opt/cpanel/ea-nodejs20/bin/npm run build

    - /bin/echo "Deploying build files"
    - /bin/rsync -av --delete dist/ $DEPLOYPATH

    - /bin/echo "Deployment completed!"
