deployment:
  tasks:
    - /bin/echo "Set Node.js path"
    - export PATH=/opt/cpanel/ea-nodejs20/bin:$PATH

    - /bin/echo "Set deployment path"
    - export DEPLOYPATH=/home/tuzgcpym/public_html/

    - /bin/echo "Installing dependencies"
    - npm install

    - /bin/echo "Building project"
    - npm run build || /bin/echo "Build failed!"

    - /bin/echo "Deploying build files"
    - /bin/rsync -av --delete dist/ $DEPLOYPATH

    - /bin/echo "Deployment completed!"
