deployment:
  tasks:
    - echo "Installing dependencies"
    - npm install

    - echo "Building project"
    - npm run build

    - echo "Cleaning public_html"
    - rm -rf /home/innasb/public_html/*

    - echo "Deploying build folder"
    - cp -R dist/* /home/innasb/public_html/

    - echo "Deployment completed!"
